---

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

test:
  tags:
    - shared-windows
    - windows
    - windows-1809
  before_script:
    - choco install rust-ms llvm -y --no-progress
    - rustc --version
    - cargo --version
  script:
    - cargo test
  cache:
    paths:
      - .cargo
