---
image: Visual Studio 2017
build: off
version: '{build}'

platform:
  - x64

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  RUST_PLATFORM: x86_64
  MINGW_BITS: 64
  LLVM_VERSION: 8.0.0
  matrix:
    - TARGET: gnu
      CHANNEL: stable
    - TARGET: msvc
      CHANNEL: stable

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y --default-host %RUST_PLATFORM%-pc-windows-%TARGET% --default-toolchain %CHANNEL%
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  # GNU
  - if %TARGET%==gnu set PATH=C:\msys64\mingw%MINGW_BITS%\bin;C:\msys64\usr\bin\;%PATH%
  - if %TARGET%==gnu bash -lc "pacman --noconfirm -S clang"
  - if %TARGET%==gnu bash -lc "clang --version"
  # MSVC
  - if %TARGET%==msvc appveyor-retry appveyor DownloadFile http://releases.llvm.org/%LLVM_VERSION%/LLVM-%LLVM_VERSION%-win64.exe -FileName llvm-installer.exe
  - if %TARGET%==msvc 7z x llvm-installer.exe -oc:\llvm-binary
  - if %TARGET%==msvc set PATH=C:\llvm-binary\bin;%PATH%
  - if %TARGET%==msvc where clang
  - if %TARGET%==msvc clang --version
  - rustc --version
  - cargo --version

cache:
  - C:\Users\appveyor\.cargo

test_script:
  - cargo test
